Adding flipped option to unicode representation
niklasf/python-chess pull request #909
Opened 2022-07-21 00:23 UTC by DonLarry

chess.svg.board has the option to be flipped, so I thought Unicode representation could also have a reversed/flipped option, which is the feature this commits adds.

2022-07-22 10:17 UTC, niklasf requested changes

2022-07-22 10:17 UTC, niklasf commented on chess/__init__.py
> +    def unicode(self, *, invert_color: bool = False, borders: bool = False, empty_square: str = "⭘", flipped:bool = False) -> str:
`orientation` is preferable in `chess.svg`. Let's use it here, too.

https://github.com/niklasf/python-chess/blob/aa0a04f37da9339b7d3a983aecbe9c97935fc0d3/chess/svg.py#L292-L293

2022-07-22 10:17 UTC, niklasf commented on chess/__init__.py
> +
This transformation will not change the coordinates if `board.unicode(..., borders=True)`. Best to change the actual iteration order instead.

2022-07-29 00:07 UTC, DonLarry commented
Hi @niklasf, I think I've applied all the suggestions you gave me :)

2022-07-29 06:38 UTC, merged

2022-07-29 06:38 UTC, niklasf commented
Thanks!