Add square_manhattan_distance and square_knight_distance functions
niklasf/python-chess pull request #986
Opened 2023-04-08 01:01 UTC by AInnuganti

The chess library includes a function called square_distance, which calculates the Chebyshev distance (number of king steps) between 2 squares. This way of measuring distance is not always sufficient though, so I added two new distance functions.

- square_manhattan_distance calculates the Manhattan or Taxicab distance between 2 squares. This is the minimal number of orthogonal king moves it would take to travel from one square to another.

- square_knight_distance calculates the knight distance (using a pretty weird formula), which is the minimal number of knight moves to travel from one square to another

2023-04-09 11:28 UTC, niklasf requested changes
Thanks! Looks like a useful and consistent addition.

Some tests in `test.py` (`class SquareTestCase`) would be good, especially for the knight distance.

2023-04-09 11:28 UTC, niklasf commented on chess/__init__.py
> +        if 1 << a & BB_CORNERS or 1 << b & BB_CORNERS: # Special case only for corner squares
the pattern used elsewhere for this is `BB_SQUARES[a] & BB_CORNERS`

2023-04-09 11:28 UTC, niklasf commented on chess/__init__.py
> +    if a == b:
let's not special-case `a == b` in any of the implementations

2023-04-09 18:49 UTC, AInnuganti commented
Alright both of those changes have been made. I can add some test cases later

2023-04-16 03:35 UTC, AInnuganti commented
I've added tests for `square_manhattan_distance ` and `square_knight_distance`, and just for good measure, also added some for `square_distance`. Everything seems to be in working order

2023-04-16 07:40 UTC, merged

2023-04-16 07:41 UTC, niklasf commented
Looks good. Merging.